### PR TITLE
Port coq-bits to Coq 8.7 / Mathcomp 1.6.2 - Coq 8.9 / Mathcomp 1.9.0

### PR DESCRIPTION
**Pull request by anton-trunov**
I have tested that the library compiles at the two extreme points. Hopefully it does for the ranges in between.
I also check that it compiles with the current (as of today) `dev` versions of both Coq and Mathcomp.

If you decide to merge this patch, I can prepare a PR to re-add coq-bits (and at a later time coq-bitset) to opam.

### CODE REVIEW

**Comment by artart78** [comment]
Hello,
I have no plan to work on this project anymore, so you should probably just work on your own fork, the license is pretty open so you shouldn't really have limitations (including re-adding stuff to opam, etc).

Also, if you didn't already see it, you should check https://github.com/ejgallego/ssrbit which is in a more sketchy state as far as I remember but might have a better code structure.

Regards

**Comment by anton-trunov** [comment]
Thank you for getting back to me. There is a [coq-community](https://github.com/coq-community/manifesto) GitHub organization, one of its goals is

> Projects can be hosted in coq-community in one of the following case:
> the initial author has stopped maintaining the project and someone else is volunteering to do so;

Would you mind transferring the ownership of the project to coq-community? I'm willing to maintain compatibility with future Coq/Mathcomp versions. If you are fine with this, I'll open an issue on coq-community/manifesto repo to facilitate the transfer.

> Also, if you didn't already see it, you should check https://github.com/ejgallego/ssrbit which is in a more sketchy state as far as I remember but might have a better code structure.

Yes, I'm aware of this, thank you. It would be great to develop ssrbit further, this is why I'd like to keep coq-bits on float.

**Comment by artart78** [comment]
Hello, and sorry for the delay (for some reason I was busy when I read your message and forgot about it),

I have absolutely no problem with transferring the ownership to coq-community. Actually I'm even wondering why you need my approval since the Apache license of the project seems to allow you to do whatever you want with it? Anyway, if you need approval from the authors you should also get @pedagand 's one.

Please tell me if you need me to do anything (and to ping me again if I disappear again ;))

**Comment by anton-trunov** [comment]
Thank you very much for getting back to me!

> I have absolutely no problem with transferring the ownership to coq-community. 

Great, I opened https://github.com/coq-community/manifesto/issues/79 to facilitate the process.

> Actually I'm even wondering why you need my approval since the Apache license of the project seems to allow you to do whatever you want with it

If we do it this way GitHub keeps all the metadata belonging to this repo: issues, PR, etc (in this case it seems to not matter). I'm not sure if this is true, the links to this repo should be redirected to the coq-community's repo by GitHub as well. And having just one copy of the repo should create no confusion for people who might be interested in contributing in the future.

By the way, this link explains how to do transfers in six easy steps :)
https://help.github.com/en/articles/transferring-a-repository#transferring-a-repository-owned-by-your-personal-account

**Comment by Zimmi48** [comment]
@artart78: thanks for accepting the transfer. We indeed prefer transfers to friendly forks for the reasons @anton-trunov listed. I will send you an invitation to coq-community, and you will need to accept it first to have the permission to transfer the repository there. Another solution is that you transfer the repository to @anton-trunov, and he subsequently transfers it to coq-community.

**Comment by Zimmi48** [comment]
ping @artart78 
Now that you have accepted the invitation to coq-community, you should be able to proceed with the transfer. Let us know if you encounter any difficulty.

**Comment by artart78** [comment]
I already transfered the repository to coq-community, unless I missed something?

**Comment by Zimmi48** [comment]
Oh, for some reason I had failed to notice. Thanks for the quick answer!

**Comment by anton-trunov** [comment]
@artart78 Awesome! Thank you very much!

**Comment by artart78** [comment]
It's also my fault for doing it without telling you ;) i thought you'd get a notification! Anyway enjoy!

**Pull request merged**
